name: Simple CI/CD Pipelin

on:
  push:
    branches:
      - main  # This workflow runs on pushes to the master branch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Test Stage
        run: echo "This is the Test stage"

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Build Stage
        run: echo "This is the Build stage"

  design:
    needs: build
    runs-on: ubuntu-latest
    name: Design Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Design Stage
        run: echo "This is the Design stage"

  maintain:
    needs: design
    runs-on: ubuntu-latest
    name: Maintain Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Maintain Stage
        run: echo "This is the Maintain stage"

  deploy:
    needs: maintain
    runs-on: ubuntu-latest
    name: Deploy Stage
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Echo Deploy Stage
        run: echo "This is the Deploy stage"
